name: Release

on:
  push:
    tags:
      - "!player/"
      - "v*"

jobs:
  test_and_build:
    uses: ./.github/workflows/ci.yml

  download_and_publish:
    needs: test_and_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install dependencies
        run: npm ci

      - name: Read package.json version
        uses: actions/github-script@v6
        id: extract-version
        with:
          script: |
            const { version } = require('./package.json')
            core.setOutput('packageJsonVersion', version)

      - uses: actions/download-artifact@v3
        with:
          path: .

      - name: Unpackage artifact files
        run: tar -xzvf artifact/artifact.tar.gz -C .
        shell: bash

      - name: Publish
        run: ./publish.sh
        shell: bash
        env:
          NPM_DRY_RUN: false
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
